myfile = open('d:\data.txt','w')
myfile.write("100\n")
myfile.write("102\n")
myfile.write("99\n")
myfile.write("89\n")
myfile.write("192\n")
myfile.write("938\n")
myfile.write("107\n")
myfile.write("241\n")
myfile.write("banyaknya bilangan genap: 4\n")
myfile.write("banyaknya bilangan ganjil:4\n")
myfile.close()
